### ISSUE TITLE
There is no .env.example in this repo

### ISSUE THREAD

**Issue by ronnidc** [agility/agilitycms-hugo-starter#1]
There is no `.env.example` in this repo.

The command `npm run start` fails local using node version 14. 

````
npm ERR! agility-hugo-ananke@1.0.0 prestart: `node agility/agility.sync.js sync preview
````

**Comment by joelvarty** [comment]
Thanks for this @ronnidc ! I have added a `.env.example` - hopefully that helps!  It's using the content from our Blog Starter template, so any Agility CMS account you have that was initiated from that starter should work, I believe.
